CREATE SCHEMA EMPLOYEE;

CREATE DOMAIN EMPLOYEE.PHONE_TYPE AS VARCHAR(20) NOT NULL CHECK (VALUE ~ '^\+?[(\+)?[0-9\s\-]+$');

CREATE DOMAIN EMPLOYEE.EMAIL_TYPE AS VARCHAR(30) NOT NULL CHECK (VALUE ~ '^[A-Za-z0-9._-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');


CREATE TABLE EMPLOYEE.EMPLOYEES(
	ID SMALLINT GENERATED ALWAYS AS IDENTITY,
	EMAIL EMAIL_TYPE,
	PASSWORD TEXT NOT NULL,
	PHONE PHONE_TYPE,
	NAME VARCHAR(50) NOT NULL,
	POWER VARCHAR(8) NOT NULL,
	CREATED_AT DATE NOT NULL DEFAULT CURRENT_DATE,
	UPDATED_AT DATE NOT NULL DEFAULT CURRENT_DATE,
	CONSTRAINT PK_EMP_ID PRIMARY KEY (ID, CREATED_AT)
) PARTITION BY RANGE (CREATED_AT);

DROP TABLE EMPLOYEE.EMPLOYEES;

CREATE TABLE EMP_2024 PARTITION OF EMPLOYEE.EMPLOYEES FOR VALUES FROM ('01-01-2024') TO ('31-12-2024');
CREATE TABLE EMP_OTHERS PARTITION OF EMPLOYEE.EMPLOYEES DEFAULT;

INSERT INTO EMPLOYEE.EMPLOYEES(EMAIL, PASSWORD, PHONE, NAME, POWER) VALUES ('admin@mail.com', 'admin', '0123456789', 'admin', 'admin');








