-----HERO-----
CREATE TABLE HOMEPAGE.HERO (
	TITLE VARCHAR(20) NOT NULL,
	MODELS SMALLINT [] NOT NULL,
	BRANDS VARCHAR(15) [] NOT NULL,
	TRANSMISSIONS VARCHAR(15) [] NOT NULL,
	TYPES VARCHAR(10) [] NOT NULL
);
INSERT INTO HOMEPAGE.HERO VALUES
	(
		'find your dream car',
		ARRAY [2019, 2020, 2021, 2022, 2023, 2024],
		ARRAY ['audi', 'lamborghini', 'porscher', 'bmw', 'ford'],
		ARRAY ['auto', 'manual'],
		ARRAY ['sedan', 'suv', 'sport', 'hatchback']
	);
SELECT * FROM HOMEPAGE.HERO;
---GET HERO IN JSONB---
SELECT JSONB_BUILD_OBJECT(
	'title', (SELECT H.TITLE),
	'filterForm', (SELECT JSONB_BUILD_OBJECT(
		'models', (SELECT TO_JSONB(H.MODELS)),
		'brands', (SELECT TO_JSONB(H.BRANDS)),
		'transmissions', (SELECT TO_JSONB(H.TRANSMISSIONS)),
		'types', (SELECT TO_JSONB(H.TYPES))
	))
) FROM HOMEPAGE.HERO H;
--CREATE FUNCTION GET HERO--
CREATE FUNCTION HOMEPAGE.GET_HERO()
RETURNS JSONB AS
$$
DECLARE
	HERO JSONB;
BEGIN
	HERO := JSONB_BUILD_OBJECT(
		'title', (SELECT H.TITLE),
		'filterForm', (SELECT JSONB_BUILD_OBJECT(
			'models', (SELECT TO_JSONB(H.MODELS)),
			'brands', (SELECT TO_JSONB(H.BRANDS)),
			'transmissions', (SELECT TO_JSONB(H.TRANSMISSIONS)),
			'types', (SELECT TO_JSONB(H.TYPES))
		))
	) FROM HOMEPAGE.HERO H;
	RETURN HERO;
END;
$$
LANGUAGE PLPGSQL;
--GET HERO IN JSONB BY FUNCTION--
SELECT * FROM HOMEPAGE.GET_HERO();
-----SERVICES-----
CREATE TABLE HOMEPAGE.SERVICES (TITLE VARCHAR(20) NOT NULL, SUBTITLE VARCHAR(20) NOT NULL, TEXT TEXT);
INSERT INTO HOMEPAGE.SERVICES VALUES ('our services', 'what we offers', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor');
CREATE TABLE HOMEPAGE.SERVICES_ITEMS (
	_ID INT GENERATED ALWAYS AS IDENTITY,
	TITLE VARCHAR(20) NOT NULL,
	TEXT TEXT NOT NULL,
	IMG VARCHAR(20) NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY (_ID)
);
INSERT INTO HOMEPAGE.SERVICES_ITEMS VALUES
	(DEFAULT, 'rental a car', 'Consectetur adipiscing elit incididunt ut labore et dolore magna aliqua. Risus commodo viverra maecenas.', 'services-1.png'),
	(DEFAULT, 'buying a car', 'Consectetur adipiscing elit incididunt ut labore et dolore magna aliqua. Risus commodo viverra maecenas.', 'services-2.png'),
	(DEFAULT, 'car maintenance', 'Consectetur adipiscing elit incididunt ut labore et dolore magna aliqua. Risus commodo viverra maecenas.', 'services-3.png'),
	(DEFAULT, 'support 24/7', 'Consectetur adipiscing elit incididunt ut labore et dolore magna aliqua. Risus commodo viverra maecenas.', 'services-4.png');
--GET SERVICES IN JSONB--
SELECT JSONB_BUILD_OBJECT(
	'title', (SELECT S.TITLE),
	'subTitle', (SELECT S.SUBTITLE),
	'text', (SELECT S.TEXT),
	'items', (SELECT JSONB_AGG(ROW_TO_JSON(SI)) FROM HOMEPAGE.SERVICES_ITEMS SI)
) FROM HOMEPAGE.SERVICES S;
--CREATE FUNCTION GET SERVICES--
CREATE FUNCTION HOMEPAGE.GET_SERVICES()
RETURNS JSONB AS
$$
DECLARE
	SERVICES JSONB;
BEGIN
	SERVICES := JSONB_BUILD_OBJECT(
		'title', (SELECT S.TITLE),
		'subTitle', (SELECT S.SUBTITLE),
		'text', (SELECT S.TEXT),
		'items', (SELECT JSONB_AGG(ROW_TO_JSON(SI)) FROM HOMEPAGE.SERVICES_ITEMS SI)
	) FROM HOMEPAGE.SERVICES S;
	RETURN SERVICES;
END;
$$
LANGUAGE PLPGSQL;
---FEATURES---
CREATE TABLE HOMEPAGE.FEATURES (TITLE VARCHAR(15) NOT NULL, SUBTITLE VARCHAR(50) NOT NULL, TEXT TEXT []);
INSERT INTO HOMEPAGE.FEATURES VALUES (
	'our features',
	'we are a trusted name in auto',
	ARRAY [
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et',
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.'
	]
);
	
CREATE TABLE HOMEPAGE.FEATURES_ITEMS (
	_ID INT GENERATED ALWAYS AS IDENTITY,
	TEXT VARCHAR(10) NOT NULL,
	IMG VARCHAR(15) NOT NULL
);
INSERT INTO HOMEPAGE.FEATURES_ITEMS VALUES
	(DEFAULT, 'engine', 'feature-1.png'),
	(DEFAULT, 'turbo', 'feature-2.png'),
	(DEFAULT, 'cooling', 'feature-3.png'),
	(DEFAULT, 'suspension', 'feature-4.png'),
	(DEFAULT, 'electrical', 'feature-5.png'),
	(DEFAULT, 'brakes', 'feature-6.png');
--GET FEATURES IN JSONB--
SELECT JSON_BUILD_OBJECT(
	'title', (SELECT F.TITLE),
	'subTitle', (SELECT F.SUBTITLE),
	'text', (SELECT F.TEXT),
	'items', (SELECT JSONB_AGG(ROW_TO_JSON(FI)) FROM HOMEPAGE.FEATURES_ITEMS FI)
) FROM HOMEPAGE.FEATURES F;
--CREATE FUNCTION GET FEATURES--
CREATE FUNCTION HOMEPAGE.GET_FEATURES()
RETURNS JSONB AS
$$
DECLARE
	FEATURES JSONB;
BEGIN
	FEATURES := JSON_BUILD_OBJECT(
		'title', (SELECT F.TITLE),
		'subTitle', (SELECT F.SUBTITLE),
		'text', (SELECT F.TEXT),
		'items', (SELECT JSONB_AGG(ROW_TO_JSON(FI)) FROM HOMEPAGE.FEATURES_ITEMS FI)
	) FROM HOMEPAGE.FEATURES F;
	RETURN FEATURES;
END;
$$
LANGUAGE PLPGSQL;
---CAR---
CREATE TABLE HOMEPAGE.CAR (TITLE VARCHAR(15) NOT NULL, SUBTITLE VARCHAR(50) NOT NULL);
INSERT INTO HOMEPAGE.CAR VALUES ('our cars', 'best vihicle offers');
--GET CAR IN JSONB--
SELECT JSONB_BUILD_OBJECT(
	'title', (SELECT C.TITLE),
	'subTitle', (SELECT C.SUBTITLE)
) FROM HOMEPAGE.CAR C;
--CREATE FUNCTION GET CAR IN JSONB--
CREATE FUNCTION HOMEPAGE.GET_CAR()
RETURNS JSONB AS
$$
DECLARE
	CAR JSONB;
BEGIN
	CAR := JSONB_BUILD_OBJECT(
		'title', (SELECT C.TITLE),
		'subTitle', (SELECT C.SUBTITLE)
	) FROM HOMEPAGE.CAR C;
	RETURN CAR;
END;
$$
LANGUAGE PLPGSQL;
---CHOOSE US---
CREATE TABLE HOMEPAGE.CHOOSEUS (TITLE VARCHAR(25) NOT NULL, TEXT TEXT, VIDEOURL TEXT NOT NULL);
INSERT INTO HOMEPAGE.CHOOSEUS VALUES ('why people choose us', 'Duis aute irure dolorin reprehenderits volupta velit dolore fugiat nulla pariatur excepteur sint occaecat cupidatat.', 'https://www.youtube.com/watch?v=sitXeGjm4Mc');
CREATE TABLE HOMEPAGE.CHOOSEUS_ITEMS (
	_ID INT GENERATED ALWAYS AS IDENTITY,
	TEXT TEXT NOT NULL,
	CONSTRAINT PK_CHOOSEUS_ITEMS_ID PRIMARY KEY (_ID)
);
INSERT INTO HOMEPAGE.CHOOSEUS_ITEMS VALUES
	(DEFAULT, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
	(DEFAULT, 'Integer et nisl et massa tempor ornare vel id orci.'),
	(DEFAULT, 'Nunc consectetur ligula vitae nisl placerat tempus.'),
	(DEFAULT, 'Curabitur quis ante vitae lacus varius pretium.');
CREATE INDEX idx_chooseus_ITEMS ON HOMEPAGE.CHOOSEUS_ITEMS(_ID);
--GET CHOOSE US IN JSONB--
SELECT JSONB_BUILD_OBJECT(
	'title', (SELECT CU.TITLE),
	'text', (SELECT CU.TEXT),
	'videoUrl', (SELECT CU.VIDEOURL),
	'items', (SELECT JSONB_AGG(ROW_TO_JSON(CUI)) FROM HOMEPAGE.CHOOSEUS_ITEMS CUI)
) FROM HOMEPAGE.CHOOSEUS CU;
--CREATE FUNCTION GET CHOOSE US IN JSONB--
CREATE FUNCTION HOMEPAGE.GET_CHOOSEUS()
RETURNS JSONB AS
$$
DECLARE
	CHOOSEUS JSONB;
BEGIN
	CHOOSEUS := JSONB_BUILD_OBJECT(
		'title', (SELECT CU.TITLE),
		'text', (SELECT CU.TEXT),
		'videoUrl', (SELECT CU.VIDEOURL),
		'items', (SELECT JSONB_AGG(ROW_TO_JSON(CUI)) FROM HOMEPAGE.CHOOSEUS_ITEMS CUI)
	) FROM HOMEPAGE.CHOOSEUS CU;
	RETURN CHOOSEUS;
END;
$$
LANGUAGE PLPGSQL;
---CTA---
CREATE TABLE HOMEPAGE.CTA (_ID INT GENERATED ALWAYS AS IDENTITY, TITLE VARCHAR(25) NOT NULL, TEXT TEXT, IMG VARCHAR(10) NOT NULL);
INSERT INTO HOMEPAGE.CTA VALUES
	(DEFAULT, 'do you want to buy a car', 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod', 'cta-1.jpg'),
	(DEFAULT, 'do you want to rent a car', 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod', 'cta-2.jpg');
--GET CTA IN JSONB--
SELECT JSONB_BUILD_OBJECT(
	'items', (SELECT JSONB_AGG(ROW_TO_JSON(C)) FROM HOMEPAGE.CTA C)
);
--CREATE FUNCTION GET CTA IN JSONB--
CREATE FUNCTION HOMEPAGE.GET_CTA()
RETURNS JSONB AS
$$
DECLARE
	CTA JSONB;
BEGIN
	CTA := JSONB_BUILD_OBJECT(
		'items', (SELECT JSONB_AGG(ROW_TO_JSON(C)) FROM HOMEPAGE.CTA C)
	);
	RETURN CTA;
END;
$$
LANGUAGE PLPGSQL;
---HOMEPAGE---
SELECT JSONB_BUILD_OBJECT(
	'hero', (SELECT * FROM HOMEPAGE.GET_HERO()),
	'services', (SELECT * FROM HOMEPAGE.GET_SERVICES()),
	'features', (SELECT * FROM HOMEPAGE.GET_FEATURES()),
	'car', (SELECT * FROM HOMEPAGE.GET_CAR()),
	'chooseus', (SELECT * FROM HOMEPAGE.GET_CHOOSEUS()),
	'cta', (SELECT * FROM HOMEPAGE.GET_CTA())
) AS HOMEPAGE;
--CREATE FUNCTION GET HOMEPAGE--
CREATE FUNCTION HOMEPAGE.GET_HOMEPAGE()
RETURNS JSONB AS
$$
DECLARE
	HOMEPAGE JSONB;
BEGIN
	HOMEPAGE := JSONB_BUILD_OBJECT(
		'hero', (SELECT * FROM HOMEPAGE.GET_HERO()),
		'services', (SELECT * FROM HOMEPAGE.GET_SERVICES()),
		'features', (SELECT * FROM HOMEPAGE.GET_FEATURES()),
		'car', (SELECT * FROM HOMEPAGE.GET_CAR()),
		'chooseus', (SELECT * FROM HOMEPAGE.GET_CHOOSEUS()),
		'cta', (SELECT * FROM HOMEPAGE.GET_CTA())
	);
	RETURN HOMEPAGE;
END;
$$
LANGUAGE PLPGSQL;
SELECT * FROM HOMEPAGE.GET_HOMEPAGE();



