---CONTACT INFO TABLE---
CREATE TABLE LAYOUT."contactInfo" (
	EMAIL VARCHAR(50) NOT NULL,
	PHONE VARCHAR(20) NOT NULL
);
INSERT INTO LAYOUT."contactInfo" VALUES (
	'hvac@mail.com',
	'(+84) 123 456 789'
);
---SCHEDULE TABLE---
CREATE TABLE LAYOUT.SCHEDULE (
	STARTAT VARCHAR(7) NOT NULL,
	ENDAT VARCHAR(7) NOT NULL
);
INSERT INTO LAYOUT.SCHEDULE VALUES ('08:00am', '09:00pm');
---TABLE SOCIALS---
CREATE TABLE LAYOUT.SOCIALS (
	FACEBOOK VARCHAR(50) NOT NULL,
	TWITTER VARCHAR(50) NOT NULL,
	INSTAGRAM VARCHAR(50) NOT NULL,
	GOOGLE VARCHAR(50) NOT NULL,
	SKYPE VARCHAR(50) NOT NULL
);
INSERT INTO LAYOUT.SOCIALS VALUES (
	'https://facebook.com',
	'https://twitter.com',
	'https://instagram.com',
	'https://google.com',
	'https://skype.com'
);
--CHECK DATA
SELECT * FROM LAYOUT."contactInfo", LAYOUT.SCHEDULE, LAYOUT.SOCIALS;